spring.application.name=procesamiento-kafka

# Configuraciones para obtener mas informacion en el log
logging.level.root=INFO
logging.level.org.hibernate=DEBUG
logging.level.org.springframework=DEBUG

#Configuración kafka
spring.kafka.bootstrap-servers=44.207.126.62:9093,44.207.126.62:9095,44.207.126.62:9097
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

## Grupo del consumidor
spring.kafka.consumer.group-id=grupo-consumidor-signos

#Configuración RabbitMQ
spring.rabbitmq.host=3.228.144.175
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

#configuraciones de server
server.port=8081